'use strict';

const rvvTraits = [
  {ch: '32.7',    m: /^v([ls]\w+).v$/,                desc: 'Vector Loads and Stores'},
  {ch: '32.7.4',  m: /^v[ls](e(8|16|32|64)|m).v$/,    desc: 'Vector Unit-Stride Instructions'},
  {ch: '32.7.5',  m: /^v[ls]se(8|16|32|64).v$/,       desc: 'Vector Strided Instructions'},
  {ch: '32.7.6',  m: /^v[ls][uo]xei(8|16|32|64).v$/,  desc: 'Vector Indexed Instructions'},
  {ch: '32.7.7',  m: /^vle(8|16|32|64)ff.v$/,         desc: 'Unit-stride Fault-Only-First Loads'},
  {ch: '32.7.8',  m: /^v[ls]\w*seg\w+.v$/,            desc: 'Vector Load/Store Segment Instructions'},
  {ch: '32.7.8.1',m: /^v[ls]seg\w+.v$/,               desc: 'Vector Unit-Stride Segment Loads and Stores'},
  {ch: '32.7.8.2',m: /^v[ls]sseg\w+.v$/,              desc: 'Vector Strided Segment Loads and Stores'},
  {ch: '32.7.8.3',m: /^v[ls][ou]xseg\w+.v$/,          desc: 'Vector Indexed Segment Loads and Stores'},
  {ch: '32.7.9',  m: /^v[ls]\dr\w*.v$/,               desc: 'Vector Load/Store Whole Register Instructions'},

  {ch: '32.10',   m: /^v[f]?\w+.v[vixf]$/,            desc: 'Vector Arithmetic Instruction Formats'},
  {ch: '32.10.2', m: /^vw\w+.[wv][vx]$/,              desc: 'Widening Vector Arithmetic Instructions'},
  {ch: '32.10.3', m: /^vn\w+.w[vx]$/,                 desc: 'Narrowing Vector Arithmetic Instructions'},

  {ch: '32.11.1', m: /^v(add|sub|rsub).v[vxi]$/,      desc: 'Vector Single-Width Integer Add and Subtract'},
  {ch: '32.11.2', m: /^vw(add|sub)[u]?.[vw][vx]$/,    desc: 'Vector Widening Integer Add/Subtract'},
  {ch: '32.11.3', m: /^v[sz]ext.vf\d$/,               desc: 'Vector Widening Integer Add/Subtract'},
  {ch: '32.11.4', m: /^v[m]?adc.v[vxi][m]?$/,         desc: 'Vector Integer Add-with-Carry / Subtract-with-Borrow Instructions'},
  {ch: '32.11.5', m: /^v(and|or|xor).v[vxi]$/,        desc: 'Vector Bitwise Logical Instructions'},
  {ch: '32.11.6', m: /^vs(ll|rl|ra).v[vxi]$/,         desc: 'Vector Single-Width Shift Instructions'},
  {ch: '32.11.7', m: /^vnsr[la].w[vxi]$/,             desc: 'Vector Narrowing Integer Right Shift Instructions'},
  {ch: '32.11.8', m: /^vms(eq|ne|ltu|lt|leu|le|gtu|gt).v[vxi]$/, desc: 'Vector Integer Compare Instructions'},
  {ch: '32.11.9', m: /^v(min|max)[u]?.v[vx]$/,        desc: 'Vector Integer Min/Max Instructions'},
  {ch: '32.11.10',m: /^vmul(h|hu|hsu)?.v[vx]$/,       desc: 'Vector Single-Width Integer Multiply Instructions'},
  {ch: '32.11.11',m: /^v(div|rem)[u]?.v[vx]$/,        desc: 'Vector Integer Divide Instructions'},
  {ch: '32.11.12',m: /^vwmul([s]?u)?.v[vx]$/,         desc: 'Vector Widening Integer Multiply Instructions'},
  {ch: '32.11.13',m: /^v(macc|nmsac|madd|nmsub).v[vx]$/, desc: 'Vector Single-Width Integer Multiply-Add Instructions'},
  {ch: '32.11.14',m: /^vwmacc(u|su|us)?.v[vx]$/,      desc: 'Vector Widening Integer Multiply-Add Instructions'},
  {ch: '32.11.15',m: /^vmerge.v[vx]m$/,               desc: 'Vector Integer Merge Instructions'},
  {ch: '32.11.16',m: /^vmv.v.[vxi]$/,                 desc: 'Vector Integer Move Instructions'},

  {ch: '32.12',   m: /^v[as](add|sub|mul)u?.v[vix]$/, desc: 'Vector Fixed-Point Arithmetic Instructions'},
  {ch: '32.12.1', m: /^vs(add|sub)u?.v[vix]$/,        desc: 'Vector Single-Width Saturating Add and Subtract'},
  {ch: '32.12.2', m: /^va(add|sub)u?.v[vix]$/,        desc: 'Vector Single-Width Averaging Add and Subtract'},
  {ch: '32.12.3', m: /^vsmul.v[vx]$/,                 desc: 'Vector Single-Width Fractional Multiply with Rounding and Saturation'},
  {ch: '32.12.4', m: /^vssr[la].v[vix]$/,             desc: 'Vector Single-Width Scaling Shift Instructions'},
  {ch: '32.12.5', m: /^vnclip(u?).w[vix]$/,           desc: 'Vector Narrowing Fixed-Point Clip Instructions'},

  {ch: '32.13',   m: /^vf\w+.(v[vf]?|w[vf])$/,        desc: 'Vector Floating-Point Instructions'},
  {ch: '32.13.2', m: /^vf(add|sub|rsub).v[vf]$/,      desc: 'Vector Single-Width Floating-Point Add/Subtract Instructions'},
  {ch: '32.13.3', m: /^vfw(add|sub).(v[vf]|w[vf])$/,  desc: 'Vector Widening Floating-Point Add/Subtract Instructions'},
  {ch: '32.13.4', m: /^vf(mul|div|rdiv).v[vf]$/,      desc: 'Vector Single-Width Floating-Point Multiply/Divide Instructions'},
  {ch: '32.13.5', m: /^vfwmul.v$/,                    desc: 'Vector Widening Floating-Point Multiply'},
  {ch: '32.13.6', m: /^vf(n?)m(acc|sac|add|sub).v[vf]$/, desc: 'Vector Single-Width Floating-Point Fused Multiply-Add Instructions'},
  {ch: '32.13.7', m: /^vfw(n?)(macc|msac).v[vf]$/,    desc: 'Vector Widening Floating-Point Fused Multiply-Add Instructions'},
  {ch: '32.13.8', m: /^vfsqrt.v$/,                    desc: 'Vector Floating-Point Square-Root Instruction'},
  {ch: '32.13.9', m: /^vfrsqrt7.v$/,                  desc: 'Vector Floating-Point Reciprocal Square-Root Estimate Instruction'},
  {ch: '32.13.10',m: /^vfrec7.v$/,                    desc: 'Vector Floating-Point Reciprocal Estimate Instruction'},
  {ch: '32.13.11',m: /^vf(min|max).v[vf]$/,           desc: 'Vector Floating-Point MIN/MAX Instructions'},
  {ch: '32.13.12',m: /^vfsgnj[nx]?.v[vf]$/,           desc: 'Vector Floating-Point Sign-Injection Instructions'},
  {ch: '32.13.13',m: /^vmf(eq|ne|lt|le|gt|ge).v[vf]$/,desc: 'Vector Floating-Point Compare Instructions'},
  {ch: '32.13.14',m: /^vfclass.v$/,                   desc: 'Vector Floating-Point Classify Instruction'},
  {ch: '32.13.15',m: /^vfmerge.vfm$/,                 desc: 'Vector Floating-Point Merge Instruction'},
  {ch: '32.13.16',m: /^vfmv.v.f$/,                    desc: 'Vector Floating-Point Move Instruction'},
  {ch: '32.13.17',m: /^vfcvt(.rtz)?.(xu|x|f).(f|xu|x).v$/, desc: 'Single-Width Floating-Point/Integer Type-Convert Instructions'},
  {ch: '32.13.18',m: /^vfwcvt(.rtz)?.(xu|x|f).(f|xu|x).v$/, desc: 'Widening Floating-Point/Integer Type-Convert Instructions'},
  {ch: '32.13.19',m: /^vfncvt(.rtz)?.(xu|x|f).(f|xu|x).w$/, desc: 'Narrowing Floating-Point/Integer Type-Convert Instructions'},

  {ch: '32.14',   m: /^vred\w+.vs$/,                  desc: 'Vector Reduction Operations'},
  {ch: '32.14.1', m: /^vred(sum|(max|min)[u]?|and|or|xor).vs$/, desc: 'Vector Single-Width Integer Reduction Instructions'},
  {ch: '32.14.2', m: /^vwredsum[u]?.vs$/,             desc: 'Vector Widening Integer Reduction Instructions'},
  {ch: '32.14.3', m: /^vfred([ou]sum|max|min).vs$/,   desc: 'Vector Single-Width Floating-Point Reduction Instructions'},
  {ch: '32.14.4', m: /^vfwred[ou]sum.vs$/,            desc: 'Vector Widening Floating-Point Reduction Instructions'},
];

module.exports = rvvTraits;
